### PR TITLE
use sourceGenerators

### LINKED ISSUE #33: use sourceGenerators and put generated code in src_managed
preliminary work for this has been done in #29.
requires #31 to be done first, more on the topic
in the old issue #24.

### PR DESCRIPTION
**Pull request by dwunsch**
fixes #33 except what is mentioned in #31 for which another PR will follow asap

### CODE REVIEW

**Review by fralken — COMMENTED** [review]
Hello, thanks for this pr. Now I see that both client and server code are generated on compile. But usually I need either client code or server code in a project, but not both.
So in `build.sbt` I have to disable one or the other like so:
`swaggerGenerateClient := false` or `swaggerGenerateServer := false` 

Wouldn't it be better to do the other way around, that is, let them disabled by default and then enable the one needed in the project?

As for the base path of the generated code, I would simply define it as `(sourceManaged in Compile).value` so that the resulting path would match the `package` in the source code (e.g `swagger.codegen.client`)

**Review by fralken — COMMENTED** [review]
Why should the plugin be disabled by default? Would it be better the other way around?

**Comment by fralken** [comment]
Hi @dwunsch I'm waiting for your feedback before merging this pr.

**Comment by dwunsch** [comment]
hi! sorry i didn't reply earlier..

my reasoning behind enabling the generation of both client and server by default was primarily that it saves the developer from having to do additional configuration. even if i only need the client, it doesn't really hurt to have the server part compiled - especially as i will probably need it for an integration test anyway.

disabling the plugin itself by default is important for multi-project builds which in my experience almost every project sooner or later requires. in those you probably do not want any swagger-related stuff in all but one of your subprojects.

**Comment by dwunsch** [comment]
(rebased onto master and resolved conflict in README.md)

**Comment by fralken** [comment]
It's ok to explicitly enable the plugin in build.sbt. It covers the multi-projects use case.

But I don't agree that it is harmless to have always both server and client compiled. Usually client and server have different configuration needs:

- a client depends on "play-ws" while a server doesn't
- a server needs to define `swaggerCodeProvidedPackage`
- a server needs to implement a controller implementation

I'm testing this on our companion example project, where we have two projects, client and server, with different configurations.

IMO it is more intuitive to explicitly enable the code generation that we need, rather than disable the one we don't need. 

Also, it would be nicer to have the paths of generated sources match package names (I know this is more a Java tradition). Since package names do not clash, it is redundant to define swagger/client, swagger/server, swagger/model folders.

**Comment by dwunsch** [comment]
ok, i'll change the default for swaggerGenerateClient and swaggerGenerateServer to false. would you set swaggerGenerateModel to false, too?

about the paths - i agree it's redundant. having a separate directory for each task has one big advantage, though: you can easily get rid of code the same task generated in an earlier run before you generate new code without interfering with any other tasks output.

nothing more annoying than leftover code forcing you to do an ```sbt clean``` that should never have been there after you changed your (swagger) source code.

**Comment by fralken** [comment]
Model code generation is usually needed, so it's ok to have swaggerGenerateModel set to true by default.

You are right for the paths, it's easier to manage them this way. 

Thanks a lot for this pr, this is a great improvement that's worth a bump in the version.

**Pull request merged**
