### PR TITLE
upgrade versions:

### PR DESCRIPTION
**Pull request by dvirf1**
- Use play stand alone client so that clients will not have to bring the entire Play Framework in order to use the Play Json and WS libraries.
- Cross build sbt (1.0.4 and 0.13.16)
- Use scala 2.12 for sbt 1

### CODE REVIEW

**Comment by dvirf1** [comment]
I also ran scalafmt.
The generated client is injected with the [standalone ws client](https://github.com/playframework/play-ws) and [a simple configuration](https://github.com/unicredit/sbt-swagger-codegen/pull/58/files#diff-6494670ded15e7e7892d76686a589f7fR136) (e.g `case class PetStoreClientConfig(host: String = "localhost", port: Int, ssl: Boolean = false)` ).

This fixes issues #55 and #56 (also supports sbt 0.13.16)

**Comment by andreaTP** [comment]
This looks great, haven't verified yet everything but looks nice!

**Comment by fralken** [comment]
Thanks @dvirf1 for this awesome PR. This is a great step towards sbt 1.x support and we are going to merge it.

Though, I kindly ask you to follow these guidelines:

- submit saparate PRs for different issues, that is, one PR for sbt 1.x/Scala 2.12 support, and one PR for standalone WS client, since they are not related.

- do not commit code that is simply a scalafmt reformatted code. This would make it easier for us to review the code. Scalafmt is disabled by default, since it is quite annoying to have the code automatically reformatted.

**Comment by dvirf1** [comment]
No problem. I believe I have time to do it tomorrow. I will update otherwise.

**Review by fralken — CHANGES_REQUESTED** [review]
Please split this in two PRs

**Comment by dvirf1** [comment]
@fralken see the [pull request for upgrading sbt](https://github.com/unicredit/sbt-swagger-codegen/pull/59).
After it is merged I will submit a new pull request for play 2.6 standalone client

**Comment by fralken** [comment]
Regarding the standalone client, I'm not sure it is a good idea to generate a case class like `case class PetStoreClientConfig` since it does not add anything to the generated code (unless it took the parameters somewhere from the swagger.yaml) but trivial defaults.

Actually I realised that the current implementation of the generated client cannot be injected (even if it has `@Inject() (WS: WSClient)` since it requires a `baseUrl` parameter (see the usage in the [companion example](https://github.com/unicredit/sbt-swagger-codegen-examples/blob/0.0.10/client/src/main/scala/eu/unicredit/Controller.scala#L30)).
It would be nice to implement an injectable configuration, so that I could write a client like:
`class Controller @Inject()(client: PetStoreClient)` where the `client` has its own WS (standalone) client and configuration injected.

**Comment by dvirf1** [comment]
@fralken It was separated since it can easily be injected. I'm using it with [MacWire](https://github.com/adamw/macwire) to create it (but you can also do it with Guice).

**Comment by fralken** [comment]
Indeed you are right. I easily injected a configuration into a PetStoreClient.

**Comment by fralken** [comment]
superseded by #59 and #60

**Pull request closed without merging**
