### PR TITLE
Add caching for all SBT tasks

### PR DESCRIPTION
**Pull request by rethab**
* not having caching meant every time we run compile, the output files
    are deleted and freshly written. in a project with multiple modules
    and big swagger files, this leads to significant unnecessary overhead.

  * also added logging so that we see when things are compiled and made
    various other cleanups in the plugin.

### CODE REVIEW

**Comment by rethab** [comment]
@andreaTP @fralken  What do you think?

Please note that I created this PR (originally) based on the tag from 0.0.11, because that is the version we are using while master is already quite different. In fact, since `master` is currently not working for us and we'd have to do quite some migration (eg. see #74), how about the following:
- Keep this on `0.0.11`
- For the refactoring on `master`, create version `0.1.0`.

After that, I'd be happy to forward-port the changes, but I think the refactoring on `master` changes so many things that incrementing the second number should be easily justified.

**Comment by fralken** [comment]
Hi @rethab, thanks for your PR. If you need this on top of version `0.0.11` we can merge it and publish a new version, say `0.0.12`. Then it would be nice for you to port this on current `master`.

For sure `master` will be version `0.1.0` because there are a lot of changes since `0.0.11` such as code generation with scalameta, no more generation of non-scala code (e.g. routes), etc.

I would like to better isolate code generation from the plugin itself, now it is tightly coupled with Play code generation. This is my roadmap towards `0.1.0`. But this requires some more work.

As for issue #74, I guess this should be fixed by the latest commits on `master`, let me know if this is the case.

**Comment by rethab** [comment]
@fralken sounds like a plan! Your code generation things are already on master though, aren't they? If so, are you going to drop them again or how shall we do this?

**Comment by fralken** [comment]
We can create a branch from commit tagged `0.0.11`, apply your PR, update version and tag to `0.0.12`, publish it and then merge it to master.

**Comment by rethab** [comment]
Nice. Could you please do that?

**Comment by fralken** [comment]
Ok, I just published version `0.0.12`. I created a branch `cache` with these commits. It would be nice if you could port this to master with a new PR.

**Comment by rethab** [comment]
See PR #76

**Pull request merged**
